podcast:
  owner:
    name: Cecil
    email: contact@cecil.app
  author: Cecil
  image: cover.png
  player:
    links:
      download: false
      open: false
defaultpages:
  podcast:
    path: podcast
    layout: podcast
    output: xsl
    uglyurl: true
    published: true
    exclude: true
