<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" />
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title><xsl:value-of select="/rss/channel/title"/> RSS Feed</title>
        <style type="text/css">
          body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 1rem;
            line-height: 1.5rem;
            color: #545454;
            background: #F1F3F4;
          }
          a, a:link, a:visited {
            color: #003E82;
            text-decoration: none;
          }
          a:hover {
            color: #000;
          }
          h1, h2, h3, p {
            margin-top: 0;
            margin-bottom: .8rem;
          }
          h2 {
            margin-bottom: .5rem;
          }
          h3 {
            font-style: italic;
          }
          audio {
            width: 100%;
          }
          .about {
            margin: .5rem 0;
            font-style: italic;
            font-size: .75rem;
            text-align: center;
            color: #9E9E9E;
          }
          main {
            max-width: 800px;
            margin: 0 auto;
            background: #FFF;
            padding: 2rem 2rem 0;
            border-radius: 4px;
          }
          aside {
            border-radius: 1rem;
            background-color: #F1F3F4;
            margin: 1rem 0 1rem 0;
            padding: 1rem;
            max-width: fit-content;
          }
          form {
            margin-bottom: auto;
          }
          input {
            min-width: 100%;
            margin-left: 0.2rem;
            padding-left: 0.2rem;
            padding-right: 0.2rem;
          }
          @media (min-width: 768px) {
            input {
              min-width: 20rem;
            }
          }
          #podcast-image {
            float: right;
            margin-left: 1rem;
          }
          #podcast-image img {
            width: 6rem;
            height: auto;
            border-radius: 5px;
          }
          #podcast-header {
            margin-bottom: 2rem;
          }
          .episode {
            clear: both;
            border-top: 1px solid #E5E5E5;
            padding-top: 2rem;
            padding-bottom: 1rem;
          }
          .episode-image img {
            width: 100px;
            height: auto;
            margin: 0 2rem 1rem 0;
            border-radius: 5px;
          }
          .episode-time {
            margin-bottom: 1rem;
            font-size: .85rem;
            color: #545d67;
          }
          .episode-meta {
            font-size: .8rem;
          }
        </style>
      </head>
      <body>
        <p class="about">This podcast RSS feed is generated by <a href="https://cecil.app">Cecil</a>.</p>
        <main>
          <div id="podcast-header">
            <xsl:if test="/rss/channel/image">
              <div id="podcast-image">
                <a>
                  <xsl:attribute name="href"><xsl:value-of select="/rss/channel/image/link"/></xsl:attribute>
                  <img>
                    <xsl:attribute name="src"><xsl:value-of select="/rss/channel/image/url"/></xsl:attribute>
                    <xsl:attribute name="title"><xsl:value-of select="/rss/channel/image/description"/></xsl:attribute>
                    <xsl:attribute name="alt"><xsl:value-of select="/rss/channel/image/title"/></xsl:attribute>
                  </img>
                </a>
              </div>
            </xsl:if>
            <h1>
              <xsl:value-of select="/rss/channel/title"/>
            </h1>
            <p><xsl:value-of select="/rss/channel/description"/></p>
            <p>
              <a>
                <xsl:attribute name="href">
                  <xsl:value-of select="/rss/channel/link[@rel='alternate']/@href"/>
                </xsl:attribute>
                Visit the podcast website →
              </a>
            </p>
            <aside>
              <p>To subscribe, copy the feed URL to your podcast reader.</p>
              <form>
                <label for="feed-url">Feed URL:</label>
                <input id="feed-url" onClick="this.select();">
                  <xsl:attribute name="type">url</xsl:attribute>
                  <xsl:attribute name="url">URL</xsl:attribute>
                  <xsl:attribute name="spellcheck">false</xsl:attribute>
                  <xsl:attribute name="value"><xsl:value-of select="/rss/channel/link[@rel='self']/@href" /></xsl:attribute>
                </input>
              </form>
            </aside>
          </div>
          <xsl:for-each select="/rss/channel/item">
            <div class="episode">
              <h2>
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="link"/>
                  </xsl:attribute>
                  <xsl:value-of select="title"/>
                </a>
              </h2>
              <div class="episode-time">
                <span><xsl:value-of select="substring(pubDate, 1, 10)" /></span> |
                <span><xsl:value-of select="format-number(floor(itunes:duration div 60), '0')" /> min</span>
              </div>
              <p>
                <audio>
                  <xsl:attribute name="controls" />
                  <xsl:attribute name="src">
                    <xsl:value-of select="enclosure/@url"/>
                  </xsl:attribute>
                </audio>
              </p>
              <div class="episode-meta">
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="enclosure/@url"/>
                  </xsl:attribute>
                  <xsl:attribute name="download" />
                  Download file
                </a> |
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="enclosure/@url"/>
                  </xsl:attribute>
                  <xsl:attribute name="target">_blank</xsl:attribute>
                  Play in new window
                </a> |
                <xsl:value-of select="format-number(number(enclosure/@length div '1024000'), '0')" /> Mo
              </div>
              <xsl:if test="description">
                <p><xsl:value-of select="description" disable-output-escaping="yes"/></p>
              </xsl:if>
            </div>
          </xsl:for-each>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
