<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" />
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title><xsl:value-of select="/rss/channel/title"/> RSS Feed</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #545454;
            background: #F1F3F4;
            line-height: 1.5;
          }
          a, a:link, a:visited {
            color: #003E82;
            text-decoration: none;
          }
          a:hover {
            color: #000;
          }
          h1, h2, h3, p {
            margin-top: 0;
            margin-bottom: 20px;
          }
          h2 {
            margin-bottom: 5px;
          }
          h3 {
            font-style: italic;
          }
          audio {
            width: 100%;
          }
          .about {
            font-style: italic;
            font-size: 10px;
            color: #9E9E9E;
            text-align: center;
            margin-top: 20px;
          }
          main {
            width: 800px;
            margin: 0 auto;
            background: #FFF;
            padding: 30px;
            border-radius: 4px;
          }
          #podcast-image {
            float: right;
            width: 150px;
            margin-bottom: 20px;
          }
          #podcast-image img {
            width: 150px;
            height: auto;
            border-radius: 5px;
          }
          #podcast-header {
            margin-bottom: 20px;
          }
          .episode {
            clear: both;
            border-top: 1px solid #E5E5E5;
            padding-top: 20px;
            padding-bottom: 20px;
          }
          .episode-image img {
            width: 100px;
            height: auto;
            margin: 0 30px 15px 0;
            border-radius: 5px;
          }
          .episode-time {
            font-size: 12px;
            color: #545d67;
            margin-bottom: 1em;
          }
          .episode-meta {
            font-size: 11px;
            font-weight: bold;
            font-style: italic;
          }
        </style>
      </head>
      <body>
        <p class="about">This podcast RSS feed is generated by <a href="https://cecil.app">Cecil</a>.</p>
        <main>
          <div id="podcast-header">
            <xsl:if test="/rss/channel/image">
              <div id="podcast-image">
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="/rss/channel/image/link"/>
                  </xsl:attribute>
                  <img>
                    <xsl:attribute name="src">
                      <xsl:value-of select="/rss/channel/image/url"/>
                    </xsl:attribute>
                    <xsl:attribute name="title">
                      <xsl:value-of select="/rss/channel/image/description"/>
                    </xsl:attribute>
                    <xsl:attribute name="alt">
                      <xsl:value-of select="/rss/channel/image/title"/>
                    </xsl:attribute>
                  </img>
                </a>
              </div>
            </xsl:if>
            <h1>
              <xsl:value-of select="/rss/channel/title"/>
            </h1>
            <p><xsl:value-of select="/rss/channel/description"/></p>
            <p>
              <a>
                <xsl:attribute name="href">
                  <xsl:value-of select="/rss/channel/link"/>
                </xsl:attribute>
                Visit podcast website →
              </a>
            </p>
          </div>
          <xsl:for-each select="/rss/channel/item">
            <div class="episode">
              <h2>
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="link"/>
                  </xsl:attribute>
                  <xsl:value-of select="title"/>
                </a>
              </h2>
              <div class="episode-time">
                <span><xsl:value-of select="substring(pubDate, 1, 10)" /></span> |
                <span><xsl:value-of select="format-number(floor(itunes:duration div 60), '0')" /> min</span>
              </div>
              <p>
                <audio>
                  <xsl:attribute name="controls" />
                  <xsl:attribute name="src">
                    <xsl:value-of select="enclosure/@url"/>
                  </xsl:attribute>
                </audio>
              </p>
              <div class="episode-meta">
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="enclosure/@url"/>
                  </xsl:attribute>
                  <xsl:attribute name="download" />
                  Download file
                </a> |
                <a>
                  <xsl:attribute name="href">
                    <xsl:value-of select="enclosure/@url"/>
                  </xsl:attribute>
                  <xsl:attribute name="target">_blank</xsl:attribute>
                  Play in new window
                </a> |
                <xsl:value-of select="format-number(number(enclosure/@length div '1024000'), '0')" /> Mo
              </div>
              <xsl:if test="description">
                <p><xsl:value-of select="description" disable-output-escaping="yes"/></p>
              </xsl:if>
            </div>
          </xsl:for-each>
        </main>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
